on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.2.0
        with: 
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.demoblaze.com'
