on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.2.0
        with:
          target: 'https://www.demoblaze.com'

